image: node:20-alpine

cache:
  paths:
    - node_modules/
    - .next/cache/

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run lint
    - npm run format
  dependencies:
    - install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
  dependencies:
    - install
