image: node:20-alpine

stages:
  - install
  - lint
  - prettier
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

install:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  script:
    - npm run lint

format:
  stage: prettier
  script:
    - npm run format

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

deploy:
  stage: deploy
  script:
    # Add Deploy Script at here
    - echo "Deploying your project..."
  only:
    - main
